/**
 * HTML email templates for scheduled reports.
 */

import { DateRange } from './types';

interface EmailResult {
  subject: string;
  html: string;
}

export function buildReportEmail(
  reportType: string,
  reportName: string,
  data: unknown,
  dateRange: DateRange,
): EmailResult {
  const periodLabel = `${dateRange.from.toISOString().split('T')[0]} to ${dateRange.to.toISOString().split('T')[0]}`;

  switch (reportType) {
    case 'technician_weekly':
    case 'technician_monthly':
      return buildTechnicianEmail(reportName, data, periodLabel);
    case 'company_weekly':
    case 'company_monthly':
      return buildCompanyEmail(reportName, data, periodLabel);
    case 'health_weekly':
    case 'health_monthly':
      return buildHealthEmail(reportName, data, periodLabel);
    default:
      return buildDashboardEmail(reportName, data, periodLabel);
  }
}

// ============================================
// SHARED STYLES
// ============================================

const STYLES = {
  container: 'font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 640px; margin: 0 auto; background: #0f172a; color: #e2e8f0; padding: 32px;',
  header: 'color: #06b6d4; font-size: 24px; font-weight: 700; margin-bottom: 4px;',
  subheader: 'color: #94a3b8; font-size: 14px; margin-bottom: 24px;',
  card: 'background: #1e293b; border-radius: 12px; padding: 20px; margin-bottom: 16px; border: 1px solid #334155;',
  statLabel: 'color: #94a3b8; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px;',
  statValue: 'color: #ffffff; font-size: 28px; font-weight: 700; margin-top: 4px;',
  tableHeader: 'background: #1e293b; color: #94a3b8; font-size: 12px; text-transform: uppercase; padding: 10px 12px; text-align: left; border-bottom: 1px solid #334155;',
  tableCell: 'padding: 10px 12px; border-bottom: 1px solid #1e293b; color: #e2e8f0; font-size: 14px;',
  footer: 'color: #64748b; font-size: 12px; margin-top: 32px; padding-top: 16px; border-top: 1px solid #334155;',
} as const;

function wrapEmail(title: string, periodLabel: string, body: string): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin: 0; padding: 0; background: #020617;">
  <div style="${STYLES.container}">
    <h1 style="${STYLES.header}">${title}</h1>
    <p style="${STYLES.subheader}">${periodLabel}</p>
    ${body}
    <div style="${STYLES.footer}">
      <p>This report was automatically generated by Triple Cities Tech Reporting.</p>
      <p>To manage your report subscriptions, visit the Admin Portal.</p>
    </div>
  </div>
</body>
</html>`;
}

function statCard(label: string, value: string | number, change?: string): string {
  return `<div style="display: inline-block; width: 140px; vertical-align: top; margin-right: 16px; margin-bottom: 16px;">
    <div style="${STYLES.statLabel}">${label}</div>
    <div style="${STYLES.statValue}">${value}</div>
    ${change ? `<div style="color: #94a3b8; font-size: 12px; margin-top: 2px;">${change}</div>` : ''}
  </div>`;
}

function formatMinutes(minutes: number): string {
  if (minutes < 60) return `${Math.round(minutes)}m`;
  if (minutes < 1440) return `${(minutes / 60).toFixed(1)}h`;
  return `${(minutes / 1440).toFixed(1)}d`;
}

// ============================================
// DASHBOARD EMAIL
// ============================================

function buildDashboardEmail(name: string, data: unknown, periodLabel: string): EmailResult {
  const d = data as {
    summary: {
      totalTicketsCreated: number;
      totalTicketsClosed: number;
      overallSlaCompliance: number | null;
      totalBacklog: number;
      avgResolutionMinutes: number | null;
      topCompanies: Array<{ displayName: string; ticketCount: number }>;
      topTechnicians: Array<{ name: string; hoursLogged: number }>;
    };
  };

  const s = d.summary;

  let body = `<div style="${STYLES.card}">`;
  body += statCard('Tickets Created', s.totalTicketsCreated);
  body += statCard('Tickets Closed', s.totalTicketsClosed);
  body += statCard('SLA Compliance', s.overallSlaCompliance !== null ? `${s.overallSlaCompliance}%` : 'N/A');
  body += statCard('Backlog', s.totalBacklog);
  body += statCard('Avg Resolution', s.avgResolutionMinutes !== null ? formatMinutes(s.avgResolutionMinutes) : 'N/A');
  body += '</div>';

  // Top companies
  if (s.topCompanies.length > 0) {
    body += `<div style="${STYLES.card}">`;
    body += '<h3 style="color: #e2e8f0; font-size: 16px; margin-bottom: 12px;">Top Companies</h3>';
    body += '<table style="width: 100%; border-collapse: collapse;">';
    body += `<tr><th style="${STYLES.tableHeader}">Company</th><th style="${STYLES.tableHeader}; text-align: right;">Tickets</th></tr>`;
    for (const c of s.topCompanies) {
      body += `<tr><td style="${STYLES.tableCell}">${c.displayName}</td><td style="${STYLES.tableCell}; text-align: right;">${c.ticketCount}</td></tr>`;
    }
    body += '</table></div>';
  }

  // Top technicians
  if (s.topTechnicians.length > 0) {
    body += `<div style="${STYLES.card}">`;
    body += '<h3 style="color: #e2e8f0; font-size: 16px; margin-bottom: 12px;">Top Technicians</h3>';
    body += '<table style="width: 100%; border-collapse: collapse;">';
    body += `<tr><th style="${STYLES.tableHeader}">Technician</th><th style="${STYLES.tableHeader}; text-align: right;">Hours</th></tr>`;
    for (const t of s.topTechnicians) {
      body += `<tr><td style="${STYLES.tableCell}">${t.name}</td><td style="${STYLES.tableCell}; text-align: right;">${t.hoursLogged}h</td></tr>`;
    }
    body += '</table></div>';
  }

  return {
    subject: `${name} - Service Desk Report (${periodLabel})`,
    html: wrapEmail(name, periodLabel, body),
  };
}

// ============================================
// TECHNICIAN EMAIL
// ============================================

function buildTechnicianEmail(name: string, data: unknown, periodLabel: string): EmailResult {
  const d = data as {
    summary: Array<{
      firstName: string;
      lastName: string;
      ticketsClosed: number;
      hoursLogged: number;
      avgResolutionMinutes: number | null;
      firstTouchResolutionRate: number | null;
    }>;
  };

  let body = `<div style="${STYLES.card}">`;
  body += '<table style="width: 100%; border-collapse: collapse;">';
  body += `<tr>
    <th style="${STYLES.tableHeader}">Technician</th>
    <th style="${STYLES.tableHeader}; text-align: right;">Closed</th>
    <th style="${STYLES.tableHeader}; text-align: right;">Hours</th>
    <th style="${STYLES.tableHeader}; text-align: right;">Avg Res</th>
    <th style="${STYLES.tableHeader}; text-align: right;">FTR%</th>
  </tr>`;

  for (const tech of d.summary) {
    body += `<tr>
      <td style="${STYLES.tableCell}">${tech.firstName} ${tech.lastName}</td>
      <td style="${STYLES.tableCell}; text-align: right;">${tech.ticketsClosed}</td>
      <td style="${STYLES.tableCell}; text-align: right;">${tech.hoursLogged}h</td>
      <td style="${STYLES.tableCell}; text-align: right;">${tech.avgResolutionMinutes !== null ? formatMinutes(tech.avgResolutionMinutes) : '-'}</td>
      <td style="${STYLES.tableCell}; text-align: right;">${tech.firstTouchResolutionRate !== null ? `${tech.firstTouchResolutionRate}%` : '-'}</td>
    </tr>`;
  }

  body += '</table></div>';

  return {
    subject: `${name} - Technician Report (${periodLabel})`,
    html: wrapEmail(name, periodLabel, body),
  };
}

// ============================================
// COMPANY EMAIL
// ============================================

function buildCompanyEmail(name: string, data: unknown, periodLabel: string): EmailResult {
  const d = data as {
    summary: Array<{
      displayName: string;
      ticketsCreated: number;
      ticketsClosed: number;
      supportHoursConsumed: number;
      slaCompliance: number | null;
      healthScore: number | null;
    }>;
  };

  let body = `<div style="${STYLES.card}">`;
  body += '<table style="width: 100%; border-collapse: collapse;">';
  body += `<tr>
    <th style="${STYLES.tableHeader}">Company</th>
    <th style="${STYLES.tableHeader}; text-align: right;">Created</th>
    <th style="${STYLES.tableHeader}; text-align: right;">Closed</th>
    <th style="${STYLES.tableHeader}; text-align: right;">Hours</th>
    <th style="${STYLES.tableHeader}; text-align: right;">SLA%</th>
    <th style="${STYLES.tableHeader}; text-align: right;">Health</th>
  </tr>`;

  for (const c of d.summary) {
    body += `<tr>
      <td style="${STYLES.tableCell}">${c.displayName}</td>
      <td style="${STYLES.tableCell}; text-align: right;">${c.ticketsCreated}</td>
      <td style="${STYLES.tableCell}; text-align: right;">${c.ticketsClosed}</td>
      <td style="${STYLES.tableCell}; text-align: right;">${c.supportHoursConsumed}h</td>
      <td style="${STYLES.tableCell}; text-align: right;">${c.slaCompliance !== null ? `${c.slaCompliance}%` : '-'}</td>
      <td style="${STYLES.tableCell}; text-align: right;">${c.healthScore !== null ? Math.round(c.healthScore) : '-'}</td>
    </tr>`;
  }

  body += '</table></div>';

  return {
    subject: `${name} - Company Report (${periodLabel})`,
    html: wrapEmail(name, periodLabel, body),
  };
}

// ============================================
// HEALTH EMAIL
// ============================================

function buildHealthEmail(name: string, data: unknown, periodLabel: string): EmailResult {
  const d = data as {
    scores: Array<{
      displayName: string;
      overallScore: number;
      tier: string;
      trend: string | null;
    }>;
    distribution: {
      healthy: number;
      needsAttention: number;
      atRisk: number;
      critical: number;
    };
  };

  let body = `<div style="${STYLES.card}">`;
  body += '<h3 style="color: #e2e8f0; font-size: 16px; margin-bottom: 12px;">Health Distribution</h3>';
  body += statCard('Healthy', d.distribution.healthy);
  body += statCard('Needs Attention', d.distribution.needsAttention);
  body += statCard('At Risk', d.distribution.atRisk);
  body += statCard('Critical', d.distribution.critical);
  body += '</div>';

  body += `<div style="${STYLES.card}">`;
  body += '<table style="width: 100%; border-collapse: collapse;">';
  body += `<tr>
    <th style="${STYLES.tableHeader}">Company</th>
    <th style="${STYLES.tableHeader}; text-align: right;">Score</th>
    <th style="${STYLES.tableHeader}; text-align: center;">Tier</th>
    <th style="${STYLES.tableHeader}; text-align: center;">Trend</th>
  </tr>`;

  for (const s of d.scores) {
    const scoreColor = s.overallScore >= 80 ? '#10b981' : s.overallScore >= 60 ? '#06b6d4' : s.overallScore >= 40 ? '#f97316' : '#ef4444';
    body += `<tr>
      <td style="${STYLES.tableCell}">${s.displayName}</td>
      <td style="${STYLES.tableCell}; text-align: right; color: ${scoreColor}; font-weight: 700;">${Math.round(s.overallScore)}</td>
      <td style="${STYLES.tableCell}; text-align: center;">${s.tier}</td>
      <td style="${STYLES.tableCell}; text-align: center;">${s.trend || 'stable'}</td>
    </tr>`;
  }

  body += '</table></div>';

  return {
    subject: `${name} - Customer Health Report (${periodLabel})`,
    html: wrapEmail(name, periodLabel, body),
  };
}
