import { NextRequest } from 'next/server'
import JSZip from 'jszip'
import { auth } from '@/auth'
import { getCampaignAssets, getDocBySlug, getSocialDocBySlug, campaignTitle } from '@/lib/documents/store'
import { renderSocialCard, deriveCardCopy } from '@/lib/documents/social-card'
import { renderBrandedHtml } from '@/lib/documents/export-html'
import { composePost, platformInfo } from '@/lib/documents/social-types'

export const dynamic = 'force-dynamic'
export const maxDuration = 120

function safe(name: string): string {
  return (
    name
      .replace(/[^a-z0-9-_ ]+/gi, '')
      .trim()
      .replace(/\s+/g, '-')
      .slice(0, 60) || 'asset'
  )
}

/** Build a single branded zip of every rebranded asset in a campaign. */
export async function GET(_request: NextRequest, { params }: { params: Promise<{ slug: string }> }) {
  const session = await auth()
  if (!session) return new Response('Unauthorized', { status: 401 })

  const { slug } = await params
  const assets = await getCampaignAssets(slug)
  if (assets.length === 0) return new Response('Not found', { status: 404 })

  const title = campaignTitle(slug)
  const zip = new JSZip()
  const readme: string[] = [`${title} — TCT-branded campaign`, '', 'Generated by Triple Cities Tech. Contents:', '']

  try {
    for (const a of assets) {
      const shortTitle = a.title.replace(new RegExp(`^${title}\\s*—\\s*`), '')
      if (a.docType === 'social') {
        const d = await getSocialDocBySlug(a.slug)
        if (!d) continue
        const captions: string[] = [`${title} — social posts`, '']
        for (let i = 0; i < d.posts.length; i++) {
          const p = d.posts[i]
          const { headline, subhead } = deriveCardCopy(p.note, p.body)
          for (const size of ['1200x628', '800x800'] as const) {
            const img = renderSocialCard({ headline, subhead, size })
            zip.file(`social/Ad-${i + 1}-${size}.png`, Buffer.from(await img.arrayBuffer()))
          }
          captions.push(`=== Post ${i + 1} — ${platformInfo(p.platform).label} ===`, composePost(p), '')
        }
        zip.file('social/captions.txt', captions.join('\n'))
        readme.push(`social/ — ${d.posts.length} branded cards (1200x628 + 800x800) + captions.txt`)
      } else {
        const d = await getDocBySlug(a.slug)
        if (!d) continue
        const kind = a.assetKind || 'content'
        const base = `${kind}/${safe(shortTitle)}`
        zip.file(`${base}.md`, `# ${d.title}\n\n${d.deck ? d.deck + '\n\n' : ''}${d.body}\n`)
        zip.file(`${base}.html`, renderBrandedHtml({ title: d.title, deck: d.deck, body: d.body, kind }))
        readme.push(`${base}.html / .md — ${shortTitle}`)
      }
    }

    zip.file('README.txt', readme.join('\n'))
    const data = await zip.generateAsync({ type: 'arraybuffer' })
    return new Response(data, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${slug}-tct-branded.zip"`,
        'Cache-Control': 'no-store',
      },
    })
  } catch (err) {
    console.error('[documents:export] failed:', err)
    return new Response('Export failed: ' + (err as Error).message, { status: 500 })
  }
}
